### ISSUE TITLE
Manual type locations for URN-style links

### ISSUE THREAD

**Issue by TohruKohrita** [commercetools/commercetools-docs-kit#1000]
The Link component has to respect the manual type locations when rendering URN-style links (render only if the link can be resolved). 

If the link is not resolved, we would like to have the link text rendered as a plain text. (When I tested on a local branch, link text was clickable and the link was broken whereas [this smoke test example](https://commercetools-docs-kit-git-ao-document-lin-07a241-commercetools.vercel.app/api-docs-smoke-test/links/link-to-soft-link#linking-from-description-of-a-type) does not render the link text at all.)

**Comment by nkuehn** [comment]
the way that link is written is not a "real" URN link.  It's a URL that uses the  anchor that is generated instead of pointing to the heading anchor. 

If we link to a page anyways the link is implying a given site and page structure.  In that context, it is better to link to the heading instead of to the rendered API element.   LInking to a heading is better because the heading is visible after navigation and the URL makes more sense. 

->  please update the README to not recommend unsuitable patterns that mix URL and URN linking.

**Comment by davifantasia** [comment]
TODO: Need to clarify problem with @TohruKohrita . The current description highlights two challenges:

1. Can't use links to render the manually typed location of types.
2. Invalid/unresolved links should be rendered as plain text.

**Comment by nkuehn** [comment]
@davifantasia  I think this is obsolete if you merge #1018

**Comment by AgaMillward** [comment]
Timon told me to close it :P
