### ISSUE TITLE
Rendering for info boxes is missing in RAML descriptions

### ISSUE THREAD

**Issue by adinakleine** [commercetools/commercetools-docs-kit#1058]
The possibility of rendering an information in an info (or warning) box is sometimes useful (and needed). For example if something is not following the standard behaviour. 
This is currently not possible in RAML descriptions. 
Please evaluate this.

**Comment by nkuehn** [comment]
This is not supposed to happen by design.  Description Markdown in RAML can end up in deeply nested places like a table cells in a table in a grey box of an Endpoint.   Anything that creates layout with own block boxes is explicitly disabled in the implementation.  

Even paragraphs are discouraged and should be avoided in RAML descriptions.   RAML is still mainly the API surface specification and should not become a replacement for body text content, which is better written in the mardkdown / MDX of the actual pages.
