### ISSUE TITLE
RAML: Spaces being inserted for thousands/millions separators

### ISSUE THREAD

**Issue by industrian** [commercetools/commercetools-docs-kit#1180]
While reviewing https://github.com/commercetools/commercetools-docs/pull/1333 I noticed that the values for `Maximum` has spaces for thousand/million/etc separators. Other values don't seem to have this.

![image](https://user-images.githubusercontent.com/77231096/147752744-94255fd6-ecfd-422b-a2b8-eed29b10405b.png)

I did some testing locally and got the following:

![image](https://user-images.githubusercontent.com/77231096/147752722-4e744179-213b-43b0-a35f-7e402dfc6701.png)

![image](https://user-images.githubusercontent.com/77231096/147752734-c963bd16-c567-4f48-b8ee-577b9a931e7e.png)

I accidentally created this issue in the docs repo (https://github.com/commercetools/commercetools-docs/issues/1675) and have since closed that one.

**Comment by nkuehn** [comment]
We cannot fix this reliably.  It's rooted in teh RAML specification.   `default` is a string field because it's applicable to properties that can be a string, number, whatever.  So it's not possible to safely assume that `10000` is actually intended t be a number. 
`minimum` and `maximum` are number fields that can safely be formatted as a number. 

I tried to implement is and it got excessively complex compared to the impact.  

 I suggest to close this as "wontfix" due to being too complex  and hacky to be worth it.

**Comment by adinakleine** [comment]
> We cannot fix this reliably. It's rooted in teh RAML specification. `default` is a string field because it's applicable to properties that can be a string, number, whatever. So it's not possible to safely assume that `10000` is actually intended t be a number. `minimum` and `maximum` are number fields that can safely be formatted as a number.
> 
> I tried to implement is and it got excessively complex compared to the impact.
> 
> I suggest to close this as "wontfix" due to being too complex and hacky to be worth it.

@nkuehn Okay... we can live with it. I'll close it.
