### ISSUE TITLE
Java code examples are not highlighted

### ISSUE THREAD

**Issue by industrian** [commercetools/commercetools-docs-kit#1261]
In the docs smoke test, Java code examples are highlighted: https://commercetools-docs-kit.vercel.app/docs-smoke-test/views/code-examples#java

In the docs website they're not. This is regardless of them being a code example from a file or in a code block.

![image](https://user-images.githubusercontent.com/77231096/159462420-f37b2026-9112-4656-b3cd-bc52b2574aa2.png)
![image](https://user-images.githubusercontent.com/77231096/159462602-ad18254d-c8c2-40bf-bb03-555b344e17a7.png)

Another good example being the [current Java SDK page](https://docs.commercetools.com/sdk/jvm-sdk#features).

I was testing with the example code in the docs smoke test, but as you can see above it also affects any Java code:

```java
public class MyClass {
  public static void main(String[] args) {
    System.out.println("Hello World");
  }
}
```

```java
    System.out.println("Hello World");  
```

**Comment by nkuehn** [comment]
@industrian  I think I have a potential culprit, which is due to lack of proper documentation in the kit:

https://commercetools-docs-kit.vercel.app/documentation/configuration/setup#folder-structure  (nearest heading, it does not directly have to do with this)

The `additionalPrismLanguages`  configuration flag was never actually set in the conent repository, that means it relies on whatever Prism (the syntax highlighter library) ships built-in in any given version.  The kit smoke test explicitly sets the supported languages so I guess it is a regression with some prism version that went undetected in the kit repo but popped up in your case. 

Kit config:  https://github.com/commercetools/commercetools-docs-kit/blob/main/websites/documentation/gatsby-config.js#L20

content repo: https://github.com/commercetools/commercetools-docs/blob/main/packages/gatsby-theme-docs-base/configure-theme.js#L7  (not public just in case someone wonders)

**Comment by industrian** [comment]
@nkuehn 

Defining the `additionalPrismLanguages` in gatsby-config.js has added code highlighting, as below (running locally):

![image](https://user-images.githubusercontent.com/77231096/160417696-5add0617-038f-48fe-9dd8-f8b2bcf68673.png)

**Comment by nkuehn** [comment]
great, thank you for the fast feedback!
