### ISSUE TITLE
Provide URN-style resolution for API Endpoints

### ISSUE THREAD

**Issue by timonrey** [commercetools/commercetools-docs-kit#1343]
Currently, the Endpoint URNs are not being resolved by the theme. We already have the general code but the RAML description is not being checked for endpoints, only for types.

Place of implementation:
https://github.com/commercetools/commercetools-docs-kit/blob/main/packages/gatsby-theme-api-docs/src/utils/transform-urn-links-plugin.js

**Comment by FFawzy** [comment]
specs: https://github.com/commercetools/commercetools-docs-kit/blob/2c9e3223feae810437987a71a546631f0c404aa5/packages/gatsby-theme-api-docs/src/utils/ctp-urn.js#L49

**Comment by gabriele-ct** [comment]
Implementing the ticket I came across an issue that seems to be the same that it was reported a while ago in this ticket:
https://github.com/commercetools/commercetools-docs-kit/issues/1264

Essentially, in some cases, when using a link to another page containing an anchor, the navigation to the new page happens, but the scrolling to the anchor item, doesn't happen.

This seems to be related to the fact that when SPA navigation happen, the url gets update before the DOM is fully available and therefore the scroll to anchor doesn't happen because the anchor is not there.
See here: https://gajus.medium.com/making-the-anchor-links-work-in-spa-applications-618ba2c6954a

I didn't go too much in depth looking into the `packages/gatsby-theme-docs/src/components/link.js` implementation but it seems to be using the default gatsby `<Link>` which appears not to handle this particular situation properly.
See:
https://stackoverflow.com/questions/64284341/anchor-links-in-gatsbyjs-react


> For what it's worth, the documentation does a poor job of explaining the shortcoming with Link and navigate. Either can be used for linking to pages with a fragment in the URL just fine, but they do not include any behavior to scroll the browser to an element on the page identified by the anchor. That responsibility is yours, and can be easily had by exporting a shouldUpdateScroll function from gatsby-browser.js with the desired behavior.

I gave it a go to the mentioned https://github.com/brohlson/gatsby-plugin-anchor-links plugin which is addressing the issue explained above adding some additional features such as smooth scrolling with configurable scroll time.
The plugins seems to solve the issue but with the strict requirement of changing any anchor to a valid CSS selector format  meaning no `:` or `%` or `{` or `/` which seems to be used in any URN anchor ids.
This requirement comes from the fact that internally the plugin uses `document.getQuerySelector` which accepts only valid CSS selectors.

So, to resume. 
Proposed solution: introduce  `gatsby-plugin-anchor-links` for handling anchor links. This means to change the `encodeURNComponent` function and `generateTypeURN` in a way that results in a valid CSS selector string

I'm open to other ideas @nkuehn @emmenko and @timonrey 
FYI @FFawzy
