### ISSUE TITLE
Release Notes on the homepage merging feeds from different microsites

### ISSUE THREAD

**Issue by adinakleine** [commercetools/commercetools-docs-kit#1429]
Only the latest four release notes are currently displayed on the [homepage](https://docs.commercetools.com/docs/). Currently only coFe release notes are displayed. This makes it hard to access the CoCo release notes. 
Please show the usual long list again.

**Comment by timonrey** [comment]
@nkuehn Suggestion:
We take the 5 newest release notes from all feeds and display them. The current logic with the newest RN from the oldest RNs from all feeds defining the list does simply not work at the moment...

**Comment by nkuehn** [comment]
That's not true, sorry to say. nothing hardcodes 5 and the situation is showing 4 and not 5.  

The feeds themselves are limited at 10 ( https://github.com/commercetools/commercetools-docs-kit/blob/main/packages/gatsby-theme-docs/gatsby-config.js#L275)  which is needed to not produce arbitrary ex-post changes in peoples feed readers if we sometimes fix something in older release notes (like a broken link).  Also for size. 

We look at the newest among the old entries and remove those of the other feeds that are after the last one of the feed whose last is earliest.  That is necessary to have a consistent timeline of releases for the amount of time that we do show (see your own comment here: https://github.com/commercetools/commercetools-docs-kit/blob/main/packages/ui-kit/src/components/rss/rss-feeds.tsx#L75 ) .  The purpose is that there are no "missing releases" in the timeline. 

The logic _does_ work, the problem here is that RSS is not robust against feeds that have "just started" like in the frontend feed where there simply is no older release than these four, which again are newer than all the other ones in the other feeeds.   The frontend feed has four releases dated 11th.  No other feed has newer ones.  So it shows only those four because for everything earlier 

ad hoc Fix idea #1:  add at least one or two historic releases to the frontend relases feed as actual releases. 
ad hoc fix idea #2:   change the date of the "wrap up" frontend releases from 11th (migration date) to the 3rd (the actual last release in that list).  That brings up all other releases after the 3rd. 
ad hoc fix idea #3:  Do nothing, release more other stuff

"full fix for the long run" idea #1:  allow telling the RSS reader when the actual first release of that feed was.  I don't think RSS has a built-in field for that ( https://validator.w3.org/feed/docs/rss2.html ).  You could hack a custom namespaced RSS field into the feed somehow that tells readers what the actual first entry is or when the feed started to exist. 

"full fix for the long run" idea #2:  hardwire that we assume a feed should have 10 items and extend the logic that any feed with less than 10 items is not to be considered for dermining the date from which on we don't know enough. 

Both has upsides / downsides.  I would not invest here but simply add one or two of the frontend releases as actual releases and let it be a day for now.   It will pop up again though once we add a next new product.

**Comment by adinakleine** [comment]
> That's not true, sorry to say. nothing hardcodes 5 and the situation is showing 4 and not 5.
> 
> The feeds themselves are limited at 10 ( https://github.com/commercetools/commercetools-docs-kit/blob/main/packages/gatsby-theme-docs/gatsby-config.js#L275) which is needed to not produce arbitrary ex-post changes in peoples feed readers if we sometimes fix something in older release notes (like a broken link). Also for size.
> 
> We look at the newest among the old entries and remove those of the other feeds that are after the last one of the feed whose last is earliest. That is necessary to have a consistent timeline of releases for the amount of time that we do show (see your own comment here: https://github.com/commercetools/commercetools-docs-kit/blob/main/packages/ui-kit/src/components/rss/rss-feeds.tsx#L75 ) . The purpose is that there are no "missing releases" in the timeline.
> 
> The logic _does_ work, the problem here is that RSS is not robust against feeds that have "just started" like in the frontend feed where there simply is no older release than these four, which again are newer than all the other ones in the other feeeds. The frontend feed has four releases dated 11th. No other feed has newer ones. So it shows only those four because for everything earlier
> 
> ad hoc Fix idea #1: add at least one or two historic releases to the frontend relases feed as actual releases. ad hoc fix idea #2: change the date of the "wrap up" frontend releases from 11th (migration date) to the 3rd (the actual last release in that list). That brings up all other releases after the 3rd. ad hoc fix idea #3: Do nothing, release more other stuff
> 
> "full fix for the long run" idea #1: allow telling the RSS reader when the actual first release of that feed was. I don't think RSS has a built-in field for that ( https://validator.w3.org/feed/docs/rss2.html ). You could hack a custom namespaced RSS field into the feed somehow that tells readers what the actual first entry is or when the feed started to exist.
> 
> "full fix for the long run" idea #2: hardwire that we assume a feed should have 10 items and extend the logic that any feed with less than 10 items is not to be considered for dermining the date from which on we don't know enough.
> 
> Both has upsides / downsides. I would not invest here but simply add one or two of the frontend releases as actual releases and let it be a day for now. It will pop up again though once we add a next new product.

@timonrey and I decided to do ad hoc fix idea #2.

**Comment by nkuehn** [comment]
Thanks or a quick decision @adinakleine 

@timonrey let's leave this in the backlog nevertheless, it will for sure pop up again when we get the next product or API rollling in.

**Comment by FFawzy** [comment]
decision

> "full fix for the long run" idea https://github.com/commercetools/commercetools-docs-kit/pull/2: hardwire that we assume a feed should have 10 items and extend the logic that any feed with less than 10 items is not to be considered for dermining the date from which on we don't know enough.
