### ISSUE TITLE
Avoid error message for JSON types in request body + allow adding description

### ISSUE THREAD

**Issue by mar-gil** [commercetools/commercetools-docs-kit#1447]
## The problem

For two methods in a coFE API, the only restriction on the payload of the request body is that is JSON serializable. The `body` is modeled as `type: any`. ~currently modeled as `object` and it will most likely be modeled as `any` in the future~.  

This modeling with unnamed JSON data types, triggers an error when generating the docs and Gatsby displays an error message.

> FYI - This modeling is due to the purpose of the API. This API serves as a proxy layer between the frontend and customer's extensions. Any JSON serializable payloads and any HTTP methods are accepted. It depends on the project configuration. For further information, see [this thread](https://github.com/commercetools/commercetools-docs/pull/2481#discussion_r1034927551).

![image](https://user-images.githubusercontent.com/63046911/207643079-7851a1b5-dbb3-4187-8662-8d396ca88cd7.png)

### Code sample

```yaml
  post:
    is:
      - action-errorable
      - right-header
      - frontastic-locale
    description: Use the POST method to write data to a backend system. Any JSON serializable payload is accepted. The following request example adds a product to a cart. For the response, we recommend to use standard HTTP codes and `application/json` encoded content. The response will be structured [as defined by the `body` property of the action](/../frontend-development/developing-an-action-extension#1-implement-the-action). The following response example contains the updated cart information, which includes the added product.
    body:
      application/json:
        type: any
        example: !include ../examples/action-payload.json
    responses:
      200:
        description: The response will be structured [as defined by the `body` property of the action](/../frontend-development/developing-an-action-extension#1-implement-the-action). We recommend to use standard HTTP response codes and `application/json` encoded content. The following response example contains information about a cart.
        body:
          application/json:
            type: object
            example: !include ../examples/action-success.json
```
## What we would need

- It would be necessary that document generation would not fail if unnamed types are used. JSON types like `string`, `number`, `object`, `any`, and `array` should be supported.
- It would be also helpful if the name of the type was shown.

**Comment by nkuehn** [comment]
Is it inherent and actually intended in this API that the response is can literally be any arbitrary data structure?   Politely said it's a really bad practice.  

If they don't want to or cannot properly model the response I would at least challenge them to the degree that they can make it a named object type that is modeled to allow any properties.   (e.g.  one regex pattern or something like that).  That gives them to opportunity to have a description text explaining why they can't tell what data will be returned, attach examples etc. )

**Comment by mar-gil** [comment]
> when rendering the docs, Gatsby displays an error message.

Thank you @nkuehn, I have suggested this idea to the coFe team. I will keep you posted.

**Comment by mar-gil** [comment]
> Is it inherent and actually intended in this API that the response is can literally be any arbitrary data structure? Politely said it's a really bad practice.
> 
> If they don't want to or cannot properly model the response I would at least challenge them to the degree that they can make it a named object type that is modeled to allow any properties. (e.g. one regex pattern or something like that). That gives them to opportunity to have a description text explaining why they can't tell what data will be returned, attach examples etc. )

Thanks @nkuehn! I have suggested this idea to the coFE team. I will keep you posted.

**Comment by nkuehn** [comment]
An idea for implementation could be to define markdown snippets for known primitive types that are rendered into the place where normally the type would be rendered.  

For non-primitive types the current error message needs to be retained.  It's unlikely to actually happen any more for custom types because rmf-codegen has pretty strict validation. 

For example:
 * `object`:  `_Any JSON "object"_`
 * `any`: `_Any valid JSON_`
 *  `number` : `_Any JSON "number"_`
 *  etc...  for boolean, array etc.  (we have special handling for some like datetime though)

in general:
 * it's not possible to directly show the primitives' names because they are RAML builtins, not JSON primitives.  They need to be translated back
 * all available RAML builtins can be found here: https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#built-in-types 
 * only applies if the response type is `application/json`
 * other response types might have their own descriptions.  Maybe the data structure is a nested map of response mime type and then the respective description per builtin type.

**Comment by mar-gil** [comment]
@nkuehn I synced with the team about it and, in particular, with @stmeissner. We think that we can proceed with your idea for implementation.
