### ISSUE TITLE
404 page blanking out

### ISSUE THREAD

**Issue by FFawzy** [commercetools/commercetools-docs-kit#1540]
visiting an old docs link
eg. 
https://docs.commercetools.com/tutorials/getting-started#create-an-api-client

throws a 404 page (expected) but then it goes blank and throws errors in the console.

Goal
investigate it if its a simple fix we can use this ticket for the fix too,  or if it needs more effort then we can write the results of the investigation into another implementation ticket.

**Comment by gabriele-ct** [comment]
I spent some time investigating the issue and it turns out that this is only happening on the `docs` websites and not on the `docs-kit`. That seems to suggest that it's related to something specific to the `docs` setup.

The issue is related to hydration issue, the server and the client version differs and they cannot be hydrated.

Te even more strange thing is that if we try to render the 404 page directly by loading https://docs.commercetools.com/tutorials/404, the page loads fine.

I didn't go further with the investigation, but it doesn't look like a trivial issue

**Comment by gabriele-ct** [comment]
@nkuehn do you have any pointers about it? At least to have an idea about where to start looking into
