### ISSUE TITLE
Browser search results not highlighted in scroll bar

### ISSUE THREAD

**Issue by industrian** [commercetools/commercetools-docs-kit#1606]
I’m not sure if this is expected behavior or a bug, but I’ve noticed that browser search results (when using ctrl+f / command+f on a website) do not leave a mark in the scroll bar as they do on other websites and within Visual Studio Code.

In my opinion this is a useful feature that is missing from our docs.

**Comment by gabriele-ct** [comment]
Results of the investigation:

- The search result highlights are visible only if the right scrollbar is visible. In our case we hide the y axis scrollbar by setting `overflow-y: hidden` and we leave `auto` the visibility of overflow-x.
- It turns out that the visibility of the y scrollbar is affected by the overflow-x setting meaning that we cannot have `overflow-x: hidden` and `overflow-y: auto` as it will still hide the y scrollbar.
- A solution could be to set both `overflow-x` or `overflow-y` to their defaults (auto) as I did in the linked PR. However I cannot guarantee that we won't get any sideeffects.
