### ISSUE TITLE
[Moodle Investigation] make self-learning e2e more deterministic

### ISSUE THREAD

**Issue by FFawzy** [commercetools/commercetools-docs-kit#1610]
Using a single test user is causing issues as we don't always begin the e2e test from a clean state. We need to think about a way to either reset a specific user's attempts, or create a new user each time (and then delete it at the end of the test). 

With coming new features this will become soon a blocker so better to start having a thought

**Comment by FFawzy** [comment]
+ having a way to reset completion status if possible
https://github.com/commercetools/commercetools-docs-kit/pull/1632#pullrequestreview-1402657201

**Comment by FFawzy** [comment]
consider deleting the user from moodle
providing an endpoint that takes care of deleting the test user only

**Comment by gabriele-ct** [comment]
`core_user_delete_users ` seems to be working as expected also because the new user has a different userid so it cannot reference any existing tracking data.
Here I see 3 possible issues:
- Running e2e will "burn" a lot of user ids (it shouldn't be a big problem) but it's worth to mention
- We need to add an additional call to get the userid based on the user email
- There might be concurrency issues if 2 e2e are running at the same time the second might delete the user used by the first one

**Comment by FFawzy** [comment]
```mermaid

sequenceDiagram
  participant A as Browser
  participant B as Auth0
  participant C as Learn API
  participant D as Moodle
  A->>B: Initiate Signup process
  B->>A: account created
  A->>B: Initiate login process
  B->>A: logged in + JWT
  alt whatever e2e test cases 
    A->>C: get attempt
    C->>C: do stuff
    C->>D: get attempt
    C->>A: attempt
 end
  A->>C: Delete user + session cookie + JWT (get user details from cookie)
  C->>D: delete user
  C->>B: delete user
  C->>A: 200

```

maybe we can do something like this WDYT? @nkuehn @gabriele-ct

**Comment by FFawzy** [comment]
One disadvantage of the above approach (sequence diagram), it will increase the costs of Auth0 as we are charged for monthly active users .. and this way we will have a lot of test users instead of just one

**Comment by gabriele-ct** [comment]
@FFawzy, thank you for taking the time to make the diagram.
my 2 cents. If we go this way:
- Signup and user deletion should happen via API endpoint. It would be great to have a `users/create-test-user` that returns the username(email) and password? of the freshly created test user. And a specular `users/delete-test-user/[user-email]` that does the clean up.
- If we implement the point above we could even go one step further and delete the user both form moodle and auth0 (don't know how complex this could be)
- We should, as discussed, add a secret `internal` token for both endpoints so that they cant be abused and make sure that both endpoints can only operate on `+test@commercetools.com` accounts

**Comment by FFawzy** [comment]
> Signup and user deletion should happen via API endpoint. It would be great to have a users/create-test-user that returns the username(email) and password?

I thought about having an e2e for signup just like we have one for login and it will be responsible for creating the account then using it in the login e2e
then when trying any endpoint the learn api middleware will upsert the new user into moodle.
 

> And a specular users/delete-test-user/[user-email] that does the clean up.

Then at the end you can send the cookie and JWT to the delete endpoint so it will be able to verify the user details and delete it from Moodle and Auth0 

this way we don't even need a secret to be passed because the secret is defacto the JWT. 
also restricting it to `+test` or whatever pattern we have for the test user emails is def a good idea too

**Comment by gabriele-ct** [comment]
@FFawzy 
It sounds reasonable approach. I can extend the [delete endpoint](https://github.com/commercetools/learning-tech/pull/422) I was working on adding the auth0 profile reset part.

- Regarding the e2e user's email pattern I was thinking something like `test.user+e2e@commercetools.com`, basically keep the `+e2e@commercetools.com` "space" in case in future we'll need other e2e users. However the delete endpoint, at least for now, it will delete only the hardcoded `test.user+e2e@commercetools.com`, no parameters.
- Regarding the auth0 part, do you think the `auth0updateUser` would be enough to reset the user profile? I can give it a go.

**Comment by FFawzy** [comment]
> I can extend the https://github.com/commercetools/learning-tech/pull/422 I was working on adding the auth0 profile reset part.
yep .. lets do that

> Regarding the e2e user's email pattern I was thinking something like test.user+e2e@commercetools.com, basically keep the +e2e@commercetools.com "space" in case in future we'll need other e2e users. However the delete endpoint, at least for now, it will delete only the hardcoded test.user+e2e@commercetools.com, no parameters.

LGTM 👍 

> Regarding the auth0 part, do you think the auth0updateUser would be enough to reset the user profile? I can give it a go.

I think so .. you should have the cookie with the auth0 data because it is sent to you from the client side and you can use the auth0 id from the cookie to clear the user data or basically set it to empty .. lets see if that easy fix would work or we need to dig up a new endpoint from Auth0 api
