### ISSUE TITLE
Bug: prints only first page

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-docs-kit#345]
We have use cases where a page must be printeable in its full length.   These include not publicly listed pages that are documented by customers as a PDF (e.g. a list of APIs, in the future price lists for training and PS services etc. ).   Currently only the first page is printed.

The most minimalist way to do it to let the div that has `.. role="application" ..` have `height: auto; width: auto;`  instead of 100vh/100vw  in a print media query.  

Printing does not have to be perfect or specially designed but at least work at all.   It's actually pretty okay,  we might opt to hide the main footer part and just leave the one with "copyright 2020 commercetools".  But that's all optional.

**Comment by emmenko** [comment]
I'm a bit confused. Is this a bug or a feature request?
What do you mean by "printing a page"? Like from the browser?

FYI: we already use a media query for Percy, so that it's able to take a full page screenshot.

In regard to this feature, how is it supposed to work? Should there be a button/link on the page that opens a "printable" version of the HTML page?

**Comment by nkuehn** [comment]
Well, if you feel better I classify this as a bug.    

Steps to reproduce:  
 1. Print from your browser. 

Expected behavior:  All content in the document in the target document (whether PDF or on paper doesn't matter here)

Current behavior (chrome):  only first page printed. 

Not sure what else to explain about printing.
