### ISSUE TITLE
Cookie consent overlay does not fade away after accepting all cookies

### ISSUE THREAD

**Issue by davifantasia** [commercetools/commercetools-docs-kit#346]
Not only does the translucent overlay not fade away, but it appears clicking on accept does not work either because after refresh, cookies are asked to be accepted again. So basically the site is unclickable and unscrollable.

### Reproduce
- Visit https://commercetools-docs-kit.now.sh/docs-smoke-test/
- Click on "Accept All Cookies"

Browser: Chrome

Image of site with overlay _before_ clicking "Accept All Cookies":
![Screenshot 2020-04-07 at 10 51 10](https://user-images.githubusercontent.com/8238495/78649514-d3747c00-78bd-11ea-857f-b4a836a5f51c.png)

Image of site with overlay _after_ clicking "Accept All Cookies":
![Screenshot 2020-04-07 at 10 49 31](https://user-images.githubusercontent.com/8238495/78649291-87293c00-78bd-11ea-9e4d-a498028db517.png)

**Comment by emmenko** [comment]
The cookie consent is supposed to "work" only on commercetools.com domains, that's why it does not get away. On the other hand, I expect it to be visible only on commercetools.com domains.

It's just a monumental shitty script.

Maybe we should render it dynamically by checking first what `window.origin` is. So if you are indeed in commercetools.com, we attach the related scripts to the dom, otherwise we don't.

I can look into it if you want.

**Comment by nkuehn** [comment]
@emmenko  let me that that one, I was able to get it done on docs.commercetools.com and we already ran that circle that the script does not work at all when dynamically attached (that's why it's in `gatsby-ssr.js` now).

**Comment by emmenko** [comment]
So what do you plan to do?

**Comment by nkuehn** [comment]
See PR #348   (do it as we successfully do on the jekyll site for over a year now to avoid throwing more worktime into this sinkhole)

**Comment by emmenko** [comment]
This is fixed now.
