### ISSUE TITLE
Design review: back to top functionality

### ISSUE THREAD

**Issue by davifantasia** [commercetools/commercetools-docs-kit#568]
The page jumps to the page title instead of the very top which includes the top menu

**Comment by emmenko** [comment]
Why? The link refers to the page heading, not the top bar.
From a user perspective, no one knows that this is a "back to top" link as intended by the design. It's not clear and thus the expectations are obviously different.

A "back to top" as you want it needs to be explicitly mention in the text link, otherwise it's not clear at all what it should do.
