### ISSUE TITLE
Use test images with content instead of just black (to detect aspect ratio issues)

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-docs-kit#671]
We have not detected an aspect ratio problem in image rendering in our manual testing because in the kit all test images are homogenous black areas which do not allow to visually see aspect ratio stretches. 

Test images should contain actual content, also to see eventual issues  created by the image transformation and compression.  

For example,  TV test images are optimized for all these things (color, resolution, rescale artifacts, aspect ratio).   Here's a good one with creative commons license and in multiple PNG rendered resolutions:  https://commons.wikimedia.org/wiki/File:PM5644.svg

**Comment by emmenko** [comment]
For info, we had flaky VRTs when we had "real" images. Using black images was a way to have the VRTs more stable.

Also, in normal viewports (for VRTs) we wouldn't have noticed the aspect ratio issue. It was only in mobile viewports noticeable.

Given that the custom image component is kind of a workaround, I'd rather have stable VRTs instead of trying to cover an edge case like this.

**Comment by nkuehn** [comment]
Thanks for remembering that, I already forgot.   Would not call aspect ratio an edge case though.  

Since it's not making things better overall I nevertheless close this then.
