### ISSUE TITLE
Restructure homepage release notes into one table

### ISSUE THREAD

**Issue by TimonRey** [commercetools/commercetools-docs-kit#722]
All release notes on the homepage for all microsites should be listed in one table.
Each entry should also contain the microsite where it's coming from.

Suggestion:

| Release Notes  |   |   |
|---|---|---|
| 26 October  | Merchant Center  | "Release note text"  |
| 20 October  | HTTP API  | "Release note text"  |
| 15 October  | HTTP API  | "Release note text"  |
| 12 October  | Import API | "Release note text"  |
etc...

**Comment by nkuehn** [comment]
Hi Timon sorry for not having come back to you yesterday.   Here's some input that may help:

Our feeds are generated with a limit of five.  If that is not enough you can increase it in this change (it's a relatively random choice, but feeds are easier to manage if they don't hold the complete history) https://github.com/commercetools/commercetools-docs-kit/blob/master/packages/gatsby-theme-docs/gatsby-config.js#L265 

if you want to be on the safe side, here's a pseudo-algorithm that should make sure the cumulative feed does not have "gaps" but could lead to only a few being listed in bad cases:
   1. fetch all feeds
   2. among the last (oldest) entries in each feed, find the one with the *newest* release date. Remember that date or entry ID.
   3. join all feeds and sort by date
   4. render but stop rendering after the entry you remembered.

This leads to the effect that the feed with the most frequent releases defines the time range defined and from the other feeds only the releases that are in that (short) time are shown at all.  It's actually right this way because it makes sure that some lesser maintained component does not take up homepage space forever with the same old release note just because it does not have any news.

**Comment by TimonRey** [comment]
@nkuehn Thanks for the update! I will implement the logic tomorrow 👍
