### ISSUE TITLE
Consider automatically using the path prefix as the `websiteName` (e.g. in sentry)

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-docs-kit#81]
The advantage of the path prefix is 
 * that it's more likely to not collide (it won't on all content hosted under the main docs domain where the sites come together)
 * saves another separate ID for the same thing.

CON: one might want to change the one but not the other later on, but do we want to encourage the names and path to be different?

**Comment by emmenko** [comment]
It's a separate field because e.g. here you don't have access to `pathPrefix`.

https://github.com/commercetools/commercetools-docs-kit/blob/01e12a2062cb6f280d40adfa666cfc1c14387853/packages/gatsby-theme-docs/gatsby-browser.js#L27

Also `pathPrefix` has a leading slash, which you don't want to have it in the sentry environment.

You could do something like:

```js
const pathPrefix = `/docs-smoke-test`;

module.exports = {
  pathPrefix,
  plugins: [
    {
      resolve: '@commercetools-docs/gatsby-theme-docs',
      options: {
        websiteName: pathPrefix.substring(1),
      },
    }
  ],
};
```

**Comment by nkuehn** [comment]
thanks, let's close it then - that's too implicit and doesn't make it better overall

Alternatively rename `websiteName` to  `websiteKey` (following commercetools conventions that a key is unique and user defined  )

**Comment by emmenko** [comment]
Yeah I suppose key or id is more appropriate or less confusing
