### ISSUE TITLE
Enabling links for a union-like type

### ISSUE THREAD

**Issue by TohruKohrita** [commercetools/commercetools-docs-kit#875]
Let T be the union-like type, "representing" the union of, say, types A, B, and C. The custom component for T renders the documentation of A, B, and C. 

A, B and C are not automatically linked when used in other types. We want them linked.

**Comment by nkuehn** [comment]
Manual linking is possible now since a recent kit version, but automatic linking would require a very significant refactoring of the codebase. 

@TohruKohrita  Could you provide some examples in the current docs?  I think there was something in the change History where a Union member used other types that are also members of another union, right?

**Comment by TohruKohrita** [comment]
This issue surfaces in the documentation if you use a custom component of a union-type to document "Action Values" because each type are used in the Action documentation. 

Luckily, there are not so many Action Values. Using a custom component for each Action Value in the MDX, I could (at least for now) avoid the problem with links.

eg. Instead of using the custom component for ChangeTargetActionValue (which is the union of 5 types), I used the custom components for these 5 types, ChangeTargetLineItemActionValue, ChangeTargetCustomLineItemActionValue, etc.

**Comment by nkuehn** [comment]
see discussion in #876 whether we should drop the Union auto-listing completely

**Comment by TohruKohrita** [comment]
We decided not to use union-type rendering feature in the docs daily on 23.03.2021.
