### ISSUE TITLE
Properties table overflows on Custom Application Testing documentation page

### ISSUE THREAD

**Issue by anilkk** [commercetools/commercetools-docs-kit#982]
Properties table component on the  Custom Application Testing documentation page overlaps with the right navigation menu, as shown below image. [Link to the Custom Application Testing page](https://docs.commercetools.com/custom-applications/development/testing).
<img width="1555" alt="Screenshot 2021-06-08 at 10 07 37" src="https://user-images.githubusercontent.com/1124415/121148597-3525d280-c842-11eb-8fa3-b4b6d9f00ebb.png">

**Comment by nkuehn** [comment]
Wontfix.  This can only be resolved by not having multiple columns with long string literals that are not allowed to break.   Allowing string literals to break in the middle would cause a lot of more significant issues in other content.  

Actually, it has been resolved because the content has been redone.
