### ISSUE TITLE
Audit Log - "Change Types" page loads very slowly

### ISSUE THREAD

**Issue by timonrey** [commercetools/commercetools-docs-kit#984]
We've noticed that the "Change Types" page loads very slowly, probably because the page has to load the types which leads to a longer loading time. Still, this needs further investigation.

Link to the page:
https://docs.commercetools.com/api/history/change-types

**Comment by nkuehn** [comment]
Short first analysis in the JS profiler of the Chrome dev tools:

![image](https://user-images.githubusercontent.com/4006139/122032241-bbf12700-cdcf-11eb-8992-1e792728eb16.png)

First research opportunities:  the useTypeLocations()  hook is 
    * either super slow in itself (a lot of recursions in it, we might have tangled up in these)
    * called way too often (move calling it up in the component tree and pass the data down?)

The Call tree view rather points towards the implementation inside the hook:

![image](https://user-images.githubusercontent.com/4006139/122033366-bea04c00-cdd0-11eb-95a9-46f81ff22c89.png)

**Comment by nkuehn** [comment]
@timonrey you could start with not touching any code, but refactoring the useTypeLocations() hook code into more explicitly named functions, so that the actual hook is just doing the static query (which is fast) and then calls functions.  Obvious first candidate: `typeLocationOverrides` generation (that nested reducer).  Once you found the spot you try to optimize. 

My first instinctive candidate is that you have a double nested reducer that at the _leaf_  level does a repetitive spread merging of objects that are in fact databases that you just push a new key into.   That way you do it there with a spread is "fancy dancy modern JS syntax" but I think what it's really doing is that for every insertion of a new entry in the indexed database of type locations you are copying the complete database and the new entry into a new object. 

In "hot path" code that is inside often called functions and then in these in nested level of loops, try to avoid expressive powerful language constructs.  Think like a C developer and use the low level operations of the language.  If you want to add something to an object as a key,  you  use  `myObject[expressionThatHoldsNewKey] = newValueExpression` my **feeling** is that this code is overengineered: 

```js
{   // a fresh new object to be allocated
   ...locationList, // merge in all existing properties one by one -> done in every step so you end up with N lists in memory holding 1..2...3..4..n properties
   [`${api.api}__${location.type}`]: {  // a new property to the object whose key is a single-enty array and the value is an object with the actual data
      url: location.href,
   },
}
```
I think it could the result of starting with a reducer at all. 

!!!  All guesswork where to potentially start, not really tried out !!!

**Comment by nkuehn** [comment]
@timonrey  I just ran the profiler again against the deployed site and despite the bad news that the page is still way too slow the good news is that the profiler pointed towards  another location in the code that has the same reducer pattern we addressed:   "convertComponentInMdxToTypeLocations"   

It's an even "hotter" path because the type locations are requested even more often (once per property of a type) and the implementation does not even seem to cache the special data structure it builds.  

Please check all the hooks for such patterns.

**Comment by timonrey** [comment]
@nkuehn thanks, I'll check the hooks and refactor them if necessary

**Comment by nkuehn** [comment]
@timonrey  we're getting there, but not there yet.  It loads at all without issues but there's still two very pronounced hotspots:
 
![image](https://user-images.githubusercontent.com/4006139/125917296-4a7b789d-8660-46c0-99f2-4ef964064217.png)

The first looks like we should keep the data structure instead of rebuilding it every time the hook is called. I introduced a caching pattern in other hooks, e.g. https://github.com/commercetools/commercetools-docs-kit/blob/main/packages/gatsby-theme-api-docs/src/hooks/use-api-types.js#L74  (it's called "index" there but that's what we are effectively building here. An indexed object that you can just access the keys in)

The other is some encodeURI call which might be a side effect or an issue on its own.  I think it's a side effect because the inner loop of the type locations hook data structure builder is calling that function.   We'll see.
